services:
  spring-api-gateway:
    image: spring-api-gateway:latest
    container_name: spring-api-gateway
    ports:
      - "9999:9999"
    env_file:
      - .env.docker
    environment:
      - SPRING_PROFILES_ACTIVE
      - SPRING_CONFIG_SERVER
      - LOKI_URL
      - KEYCLOAK_URL
      - SPRING_RABBITMQ_HOST
      - OTEL_SERVICE_NAME=spring-api-gateway
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
      - REDIS_URL
      - JAVA_OPTS
    networks:
      - labs
networks:
  labs:
    external: true
