services:
  spring-api-gateway:
    image: spring-api-gateway:latest
    container_name: spring-api-gateway
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
        reservations:
          cpus: '1.0'
          memory: 256M
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CONFIG_SERVER=${SPRING_CONFIG_SERVER}
      - LOKI_URL="loki"
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
    networks:
      - labs


networks:
  labs:
    external: true
